# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postagem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categoria',
        ),
    ]
